[package]
name = "hank"
version = "0.1.0"
authors = ["Marc Addeo <marcaddeo@gmail.com>"]

[dependencies]
irc = "0.12"
regex = "0.2"
rand = "0.3"
rafy = "0.2"
time = "0.1"
curl = "0.4.8"
serde_json = "1.0.4"
