version: 2
jobs:
  build:
    working_directory: ~/hank
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: Compile Hank
          command: cargo build --release
      - store_artifacts:
          path: target/release/hank
          destination: hank

  deploy:
    docker:
      - image: rust:latest
    steps:
      - run:
          name: Hello World
          command: echo Hello World

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
