version: 2
jobs:
  build:
    working_directory: /home/rust/src
    docker:
      - image: ekidd/rust-musl-builder:latest
    steps:
      - checkout
      - run:
          name: Compile Hank
          command: cargo build --release
      - persist_to_workspace:
          root: /home/rust/src/target/x86_64-unknown-linux-musl/release
          paths:
            - hank

  deploy:
    working_directory: /tmp
    docker:
      - image: rust:latest
    steps:
      - attach_workspace:
          at: /tmp/hank-release
      - run:
          name: Deploy Hank executable
          command: scp -oStrictHostKeyChecking=no hank hank@marc.cx:bin/hank
      - run:
          name: Restart Hank
          command: echo "Hello World!"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: master
