version: 2
jobs:
  build:
    working_directory: /home/rust/src
    docker:
      - image: ekidd/rust-musl-builder:latest
    steps:
      - checkout
      - restore_cache:
          key: cargo.registry
      - restore_cache:
          key: target-{{ checksum "Cargo.lock" }}
      - run:
          name: Compile Hank
          command: cargo build --release
      - save_cache:
          key: target-{{ checksum "Cargo.lock" }}
          paths:
            - target
      - persist_to_workspace:
          root: /home/rust/src/target/x86_64-unknown-linux-musl/release
          paths:
            - hank
      - save_cache:
          key: cargo.registry
          paths:
            - /root/.cargo

  deploy:
    working_directory: /tmp
    docker:
      - image: rust:latest
    steps:
      - attach_workspace:
          at: /tmp/release
      - run:
          name: Stop Hank
          command: ssh -oStrictHostKeyChecking=no ${DEPLOY_USER}@${DEPLOY_HOST} 'pm2 stop hank'
      - run:
          name: Deploy Hank executable
          command: scp -oStrictHostKeyChecking=no release/hank ${DEPLOY_USER}@${DEPLOY_HOST}:bin/hank
      - run:
          name: Start Hank
          command: ssh -oStrictHostKeyChecking=no ${DEPLOY_USER}@${DEPLOY_HOST} 'pm2 start hank'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: master
