version: 2
jobs:
  build:
    working_directory: /home/rust/src
    docker:
      - image: ekidd/rust-musl-builder:latest
    steps:
      - checkout
      - restore_cache:
          key: cargo.registry
      - restore_cache:
          key: target-{{ checksum "Cargo.lock" }}
      - run:
          name: Compile Hank
          command: cargo build --release
      - save_cache:
          key: target-{{ checksum "Cargo.lock" }}
          paths:
            - target
      - persist_to_workspace:
          root: /home/rust/src/target/x86_64-unknown-linux-musl/release
          paths:
            - hank
      - save_cache:
          key: cargo.registry
          paths:
            - /root/.cargo

  deploy-production:
    working_directory: /tmp/hank
    docker:
      - image: rust:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/hank/release
      - run:
          name: Deploy Hank
          command: bin/deploy $DEPLOY_USER $DEPLOY_HOST release/hank

  deploy-staging:
    working_directory: /tmp/hank
    docker:
      - image: rust:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/hank/release
      - run:
          name: Deploy Hank
          command: bin/deploy hank-staging $DEPLOY_HOST release/hank

  deploy-development:
    working_directory: /tmp/hank
    docker:
      - image: rust:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/hank/release
      - run:
          name: Deploy Hank
          command: bin/deploy hank-development $DEPLOY_HOST release/hank

workflows:
  version: 2

  production:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+.*/
            branches:
              ignore: /.*/
      - deploy-staging:
          requires:
            - build
          filters:
            tags:
              only: /^\d+\.\d+\.\d+.*/
            branches:
              ignore: /.*/
      - hold:
          type: approval
          requires:
            - deploy-staging
          filters:
            tags:
              only: /^\d+\.\d+\.\d+.*/
            branches:
              ignore: /.*/
      - deploy-production:
          requires:
            - hold
          filters:
            tags:
              only: /^\d+\.\d+\.\d+.*/
            branches:
              ignore: /.*/

  staging:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only: master

  development:
    jobs:
      - build # Run the development build job on all commits
      - deploy-development:
          requires:
            - build
          filters:
            branches:
              only: development
