version: 2
jobs:
  build:
    working_directory: /tmp/workspace
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: Compile Hank
          command: cargo build --release
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - target/release/hank

  deploy:
    working_directory: /tmp
    docker:
      - image: rust:latest
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Deploy Hank executable
          command: scp -oStrictHostKeyChecking=no workspace/target/release/hank hank@marc.cx:bin/hank

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
